"""AddColumn

Revision ID: 3a99fad3baaa
Revises: c659b6562e81
Create Date: 2025-10-14 14:31:32.720327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a99fad3baaa'
down_revision: Union[str, Sequence[str], None] = 'c659b6562e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('hash_key', sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'hash_key')
    # ### end Alembic commands ###
