"""Add_Index_RefreshToken_table

Revision ID: 5bf621c24a86
Revises: 5da3986104fd
Create Date: 2025-10-16 21:59:26.548826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf621c24a86'
down_revision: Union[str, Sequence[str], None] = '5da3986104fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_hashed_token', 'refresh_tokens', ['hashed_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_hashed_token', table_name='refresh_tokens')
    # ### end Alembic commands ###
