"""delete_hash_key

Revision ID: aded9879e2bd
Revises: 5bf621c24a86
Create Date: 2025-11-02 18:47:04.546601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aded9879e2bd'
down_revision: Union[str, Sequence[str], None] = '5bf621c24a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'hash_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('hash_key', postgresql.BYTEA(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
