"""add_column_status

Revision ID: b3079753a76e
Revises: 63e6fb8f3385
Create Date: 2025-10-06 22:49:17.382164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3079753a76e'
down_revision: Union[str, Sequence[str], None] = '63e6fb8f3385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

status_enum = sa.Enum("Usable","Unusable",name='statusenum')

def upgrade() -> None:
    """Upgrade schema."""
    status_enum.create(op.get_bind(),checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('num_messages', sa.Integer(), nullable=False))
    op.add_column('chats', sa.Column('status',status_enum, nullable=False))
    op.alter_column('chats', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('embeddings_vector_hnsw'), table_name='embeddings', postgresql_ops={'vector': 'vector_l2_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('embeddings_vector_hnsw'), 'embeddings', ['vector'], unique=False, postgresql_ops={'vector': 'vector_l2_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('chats', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('chats', 'status')
    op.drop_column('chats', 'num_messages')
    # ### end Alembic commands ###
