"""add_chunk_state_column

Revision ID: ebb1ff731f24
Revises: 036023493380
Create Date: 2025-10-11 13:33:15.398623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb1ff731f24'
down_revision: Union[str, Sequence[str], None] = '036023493380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


Chunk_status = sa.Enum("pending","failed","success" ,name='ChunkStatus')

def upgrade() -> None:
    """Upgrade schema."""
    Chunk_status.create(op.get_bind(),checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('state', Chunk_status, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'state')
    # ### end Alembic commands ###
